In [2]:
import numpy as np

### The Basics

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [6]:
# Get shape b:2x3
print(b.shape)

(2, 3)


In [21]:
# Get datatype
a.dtype

dtype('int16')

In [33]:
# Get item size
b.itemsize

8

In [34]:
# Get total size
# a.size
# a.itemsize * a.size
a.nbytes

12

### Accessing/Changing specific elements, rows, columns, etc

In [40]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [42]:
a.shape

(2, 7)

In [45]:
# Get a specific element [row, column]
# a[1, 5]
a[1, -2]

13

In [47]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
# Get a specific column
a[:, 1]

array([2, 9])

In [51]:
# Get a little more fancy [startindex:endindex+1:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [57]:
# Change value of item
a[1,5] = 20
print(a)
      
# Change value of row
a[0, 2:5:1] = [100, 101, 102]

# Change value of column
a[:, 1] = 5
print(a)

[[  1   5 100 101 102   6   7]
 [  8   5  10  11  12  20  14]]
[[  1   5 100 101 102   6   7]
 [  8   5  10  11  12  20  14]]


In [59]:
# Array 3D example
b = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [63]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

### Initializing Different Types of Arrays

In [78]:
# All 0s matrix
a = np.zeros((2,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [82]:
# All 1s matrix
b = np.ones((3,4), dtype='int32')
print(b)
print(b.shape)
print(b.size * b.itemsize)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)
48


In [88]:
# Any other number
# c = np.full((2,3), 12)
c = np.full((2,3), 12, dtype='int16')
print(c)
print(c.dtype)

[[12 12 12]
 [12 12 12]]
int16


In [90]:
# Random decimal numbers
d = np.random.rand(4,2)
print(d)

[[0.71900575 0.74456386]
 [0.42810691 0.32151151]
 [0.49808133 0.58895339]
 [0.39499034 0.9394066 ]]


In [96]:
print("Kich thuoc mang a: " + str(a.shape))
e = np.random.random_sample(a.shape)
print(e)

Kich thuoc mang a: (2, 3)
[[0.48536661 0.09846808 0.14040307]
 [0.66905782 0.34117743 0.12746965]]


In [99]:
# Random Integer numbers < 10
print("Kich thuoc mang a: " + str(a.shape))
e = np.random.randint(10, size=a.shape)
print(e)

Kich thuoc mang a: (2, 3)
[[4 3 1]
 [9 7 7]]


In [168]:
# Random Integer -6 <= numbers < 10
print("Kich thuoc mang a: " + str(a.shape))
e = np.random.randint(-6, 10, size=(3,3))
print(e)

Kich thuoc mang a: (2, 3)
[[ 9 -3  0]
 [ 2  8 -4]
 [-6 -2  5]]


In [176]:
# Repeat an array
arr = np.array([[1,2,3], [4,5,6]])
print("arr: ")
print(arr)
r1 = np.repeat(arr, 3, axis=0)
# axis=0: gấp theo chiều dọc, axis=1: gấp theo chiều ngang
print("r1: ")
print(r1)

arr: 
[[1 2 3]
 [4 5 6]]
r1: 
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [183]:
# Exercise
print("Step 1:")
output = np.full((5,5), 1)
print(output)

print("Step 2:")
z = np.full((3,3), 0)
z[1,1] = 9
print(z)

print("Step 3:")
output[1:4, 1:4] = z
print(output)

Step 1:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Step 2:
[[0 0 0]
 [0 9 0]
 [0 0 0]]
Step 3:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Be careful when copying arrays !!!!

In [185]:
# TH1: Cẩn thận khi khai báo mảng, cùng trỏ đến 1 vùng nhớ
a = np.array([1,2,3])
b = a
b[0] = 100
print(a) # not [1,2,3]

[100   2   3]


In [1]:
# Sửa tình trạng trên bằng cách
a = np.array([1,2,3])
b = a.copy() # Sửa tại đây !!!!!!!!
b[0] = 100
print(a) # same [1,2,3]

NameError: name 'np' is not defined

### Mathematics